### PR TITLE
Update #28

### PR DESCRIPTION
**Pull request by owennnnoble**

### CODE REVIEW

**Comment by rpitingolo** [comment]
@eleanorble thanks for this. I removed some unneeded format code from the middle of the program and committed that change. Please make the following edits:

- update the %let input_data_sets to equal indat.Usa_00002 
- update the %let yr to equal 2014_18 (since this is a multi-year file)
- Remember to update the Program: name in the header

Once you make those changes you should be able to re-test. Thanks!

**Comment by owennnnoble** [comment]
@rpitingolo Ready for review!

**Comment by rpitingolo** [comment]
@eleanorble thanks! I will take another look.

**Comment by rpitingolo** [comment]
@eleanorble the variables erscor50 erscor90 edscor50 edscor90 npboss50 npboss90 are no longer in ipums starting in 2018. I tried to investigate why they got dropped but the documentation isn't entirely clear. Regardless, they're not in the data anymore so I delete all of the "incg" array code.

Otherwise this looks good, please go ahead and merge this branch and final batch submit on L.

There are some new formats we need to add to the format library but I think we should do that in a separate issue and then re-batch submit these programs once the formats are updated.

**Pull request merged**
