### PR TITLE
Update #12

### PR DESCRIPTION
**Pull request by rpitingolo**
@lhendey can you review, please? I used ACS_2009_11_vacant.sas as a template. It doesn't appear that program actually filters down to only vacant units. It should only be a few lines of code if that's what you want to do, I wasn't sure.

### CODE REVIEW

**Comment by rpitingolo** [comment]
@lhendey I accidentally forgot the semicolon when I added the revisions line. Program should run now. The formats all appear to be working (I'm not entirely sure how, maybe we save them to the ipums library when adding a new year of data?) so I don't think that hierarchical formats program is necessary.

**Comment by lhendey** [comment]
@rpitingolo - but the data was downloaded in hierarchical format?

**Comment by rpitingolo** [comment]
@lhendey data was extracted in household format which is what @ptatian said to do in a comment on the issue.

**Review by lhendey — CHANGES_REQUESTED** [review]
@rpitingolo - if it's all housing units and not just vacant - perhaps we should change the label of the file and file name to hsgunits? THe .lst file on L for has many fewer obs - likely vacant units were selected before extracting?

**Comment by rpitingolo** [comment]
@lhendey here's the difference according to the documentation. 

Choose the preferred file structure for your extract: rectangular (only person records, with all requested household information attached to respective household members), hierarchical (household record followed by person records), or household-only (household records without any person records; use this only if you are interested primarily in the characteristics of housing units). The system defaults to rectangular format, which is the overwhelming choice of researchers. Note that vacant housing units are not available in rectangular data, so select one of the other options if you need data for them.

**Comment by lhendey** [comment]
@rpitingolo  or ask peter his preference for all housing units since you downloaded or filter for vacant

**Comment by rpitingolo** [comment]
@lhendey it's possible vacant units were selected before extracting. Let me look at the data on L and see if I can tell.

**Comment by rpitingolo** [comment]
@lhendey it looks like the previous files only have vacants HUs so that must have been done in the extract because there's no code in the program that seems to do it. I'll add the code here. Seems like it's not good practice to select out cases in the extract process since there's no documentation of it.

**Comment by rpitingolo** [comment]
@lhendey ready for re-review.

**Review by lhendey — APPROVED** [review]

**Pull request merged**
