### PR TITLE
Update #20

### PR DESCRIPTION
**Pull request by rpitingolo**
@lhendey ready for review.

### CODE REVIEW

**Review by lhendey — CHANGES_REQUESTED** [review]
@rpitingolo there are two uninitialized vars
NOTE: Variable pumasupr is uninitialized.
NOTE: Variable conspuma is uninitialized.

**Comment by rpitingolo** [comment]
@lhendey pumasupr and conspuma aren't on the 2012 through current ACS files. I'll remove them from the format statement.

**Review by lhendey — APPROVED** [review]

**Comment by lhendey** [comment]
@rpitingolo thanks. please merge and finalize.

**Comment by rpitingolo** [comment]
@lhendey should be good to go now.

**Pull request merged**
