### PR TITLE
read in 2012-2017 1 year ACS microdata

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@rpitingolo when I run ACS_2012 I get the error INDAT.USA_00014_2012.DATA does not exist. But it is in the right directory. I think it has to do with the data format. There's no mention of converting dataset to sas but it's what the previous programs are doing it seems. Should I use stat transfer?

**Comment by maggiesu0725** [comment]
@rpitingolo  programs are ready for review and finalize. Are we still using the Upload_ACS_yyyy.sas  to register metadata, it seems like we didn't use it for a while but it is in the instruction

**Comment by rpitingolo** [comment]
@maggiesu0725 HUD_Inc 2013 seems to be missing. Can you create it and re run the programs to test? Also please update the header comments on the programs. Thanks!

**Comment by rpitingolo** [comment]
@maggiesu0725 we use the finalize macro now so you can take the upload step out of the instructions.

**Comment by maggiesu0725** [comment]
Thanks HUD_Inc 2013 is added and the program ACS_2013 is tested. @rpitingolo

**Comment by lhendey** [comment]
@maggiesu0725 i'm getting slightly different values for 120% of AMI on hud_inc_2013 - for example for 1 person households - (37,600 (50% threshold) x 2 x 1.2=90240  - you have 90200?

**Comment by maggiesu0725** [comment]
I used this spreadsheet--L:\Libraries\IPUMS\Doc\HUD Income Limits.xlsx the formula for 120% AMI  is 
1.2*(30% AMI/0.3) so our numbers are slightly different due to rounding @lhendey

**Comment by lhendey** [comment]
@maggiesu0725 thanks.  the header fix Rob mentions hasn't been done in all the programs. the text in < > should be updated.

**Comment by maggiesu0725** [comment]
@lhendey thanks headers are updated

**Comment by lhendey** [comment]
@maggiesu0725 great - commit the changes to the headers and it should be okay to merge.

**Pull request merged**
